name: Sync Project Data to CSV Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at Midnight UTC every day
  workflow_dispatch: 

jobs:
  sync-projects:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL2: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL2 }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY2: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY2 }}
      NEXT_PUBLIC_MILESTONES_URL: 'https://milestones.projectcatalyst.io'
      KOIOS_API_KEY: ${{ secrets.KOIOS_API_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run sync script
        run: node scripts/sync-projects.js
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git add data/*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update project data in CSV files and README"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
